language: go

arch:
  - AMD64
  - ppc64le

go:
  - 1.14.x
  - 1.15.x

go_import_path: gopkg.in/src-d/go-billy.v4

install:
  - go get -v -t ./...

script:
  - make test-coverage
  - ./.ci/test-building-binaries-for-supported-os.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
